package main

import (
	"context"
	"fmt"

	"os"
	discount_ctrl "service/discount/api/controller/discount"
	"service/discount/api/handler/configs"
	handlers "service/discount/api/handler/discount"
	"service/discount/api/handler/http_util"
	_deliveryMiddleware "service/discount/api/handler/middleware"
	"service/discount/api/utils"
	"strconv"
	"time"

	"github.com/rs/zerolog"

	swagger "github.com/arsmn/fiber-swagger/v2"
	"github.com/go-playground/validator/v10"
	"github.com/gofiber/fiber/v2"
	"github.com/jackc/pgx/v5/pgxpool"

	// docs are generated by Swag CLI, you have to import them.
	_ "service/discount/api/docs" // load API Docs files (Swagger)
)

var (
	serverName, serverUrl, serverReadTimeout, alwOrg string
	pgxConnAuthDb                                    *pgxpool.Pool
	dbUsersService                                   string
	vld                                              *validator.Validate
)

func init() {
	// Server Env-
	serverName = os.Getenv("SERVER_NAME")
	if serverName == "" {
		exitf("SERVER_NAME env is required")
	}
	serverUrl = os.Getenv("SERVER_URL")
	if serverUrl == "" {
		exitf("SERVER_URL env is required")
	}
	serverReadTimeout = os.Getenv("SERVER_READ_TIMEOUT")
	if serverReadTimeout == "" {
		exitf("SERVER_READ_TIMEOUT env is required")
	}

	// Databse Master Data
	dbUsersService = os.Getenv("DB_SERVER_AUTH")
	if dbUsersService == "" {
		exitf("DB_SERVER_AUTH config is required")
	}

	// CORS
	alwOrg = os.Getenv("CORS_WHITELISTS")
	if alwOrg == "" {
		exitf("CORS_WHITELISTS config is required")
	}

}

func dbConnection() {
	var cfgAuthDb *pgxpool.Config
	var maxConnLifetime, maxConnIdleTime time.Duration
	maxConnLifetime = 5 * time.Minute
	maxConnIdleTime = 2 * time.Minute
	var err error

	cfgAuthDb, err = pgxpool.ParseConfig(dbUsersService + " application_name=" + serverName)
	if err != nil {
		exitf("Unable to create db pool config DB User E-Reviu %v\n", err)
	}
	cfgAuthDb.MaxConns = 1000                   // Maximum total connections in the pool
	cfgAuthDb.MaxConnLifetime = maxConnLifetime // Maximum lifetime of a connection
	cfgAuthDb.MaxConnIdleTime = maxConnIdleTime // Maximum time a connection can be idle
	pgxConnAuthDb, err = pgxpool.NewWithConfig(context.Background(), cfgAuthDb)
	if err != nil {
		exitf("Unable to connect to database e-reviu-auth %v\n", err)
	}

}

// @title						Template Service Auth
// @version					1.0
// @description				Template Service Auth Rest API.
// @termsOfService				http://swagger.io/terms/
// @contact.name				API Support
// @contact.email				lifelinejar@mail.com
// @license.name				Apache 2.0
// @license.url				http://www.apache.org/licenses/LICENSE-2.0.html
// @securityDefinitions.apikey	ApiKeyAuth
// @in							header
// @name						Authorization
// @BasePath					/
func main() {
	// setupLogger()
	logger := zerolog.New(os.Stdout).With().Timestamp().Logger()

	dbConnection()
	// utils.InitMinio()

	// KODE DI MAKE GO -> MINIO paling bawah
	// 	export MINIO_BASE_URL=$(MINIO_BASE_URL);\
	// export MINIO_ACCESS_KEY=$(MINIO_ACCESS_KEY);\
	// export MINIO_SECRET_KEY=$(MINIO_SECRET_KEY);\
	// export MINIO_BUCKET=$(MINIO_BUCKET);\
	// export MINIO_USE_SSL=$(MINIO_USE_SSL);\

	// close all open component
	defer func() {
		pgxConnAuthDb.Close()
	}()

	serverReadTimeoutInt, err := strconv.Atoi(serverReadTimeout)
	if err != nil {
		exitf("failed casting timeout context: ", err)
	}
	timeoutContext := time.Duration(serverReadTimeoutInt) * time.Second

	// Define a validator
	vld = utils.NewValidator()

	// Define Fiber config.
	config := configs.FiberConfig()
	app := fiber.New(config)
	middL := _deliveryMiddleware.InitMiddleware(app, &logger)
	env := os.Getenv("SERVER_LOGS_ENV")

	var level zerolog.Level
	if env == "Production" {
		level = zerolog.InfoLevel
	} else {
		level = zerolog.DebugLevel
	}

	appLogger := utils.NewAppLoggerDailyLog(level)

	app.Use(middL.CORS())
	app.Use(middL.LOGGER())
	app.Get("/", func(c *fiber.Ctx) error {
		return c.Status(fiber.StatusOK).JSON(fiber.Map{
			"status":  "success",
			"message": "You are at the root endpoint 😉",
			"data":    nil,
		})
	})

	// Swagger handler
	app.Get("/dokumentasi/discount/swagger/*", swagger.HandlerDefault)

	// strict router
	rStrict := app.Group("/ndi", middL.AuthMiddleware()) // router for api private access

	// // Panggil Handler
	// handlers.NewPostHandler(
	// 	rStrict,
	// 	vld,
	// 	auth_ctrl.NewPostController(pgxConnAuthDb, timeoutContext, appLogger),
	// )

	// Panggil Handler discount
	handlers.NewDiscountHandler(
		rStrict,
		vld,
		discount_ctrl.NewDiscountController(pgxConnAuthDb, timeoutContext, appLogger),
	)

	// Panggil Handler discount product target
	handlers.NewDiscountProductTargetHandler(
		rStrict,
		vld,
		discount_ctrl.NewDiscountProductTargetController(pgxConnAuthDb, timeoutContext, appLogger),
	)

	http_util.StartServerWithGracefulShutdown(app)
}

func exitf(s string, args ...interface{}) {
	errorf(s, args...)
	os.Exit(1)
}

func errorf(s string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, s+"\n", args...)
}
