// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "lifelinejar@mail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ndi/discount": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get all discounts",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discount"
                ],
                "summary": "List Discount",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Discounts retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/resmodel.DatasResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "404": {
                        "description": "Discounts not found",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new discount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discount"
                ],
                "summary": "Create Discount",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to check",
                        "name": "X-Auth-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create discount",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/reqmodel.CreateDiscount"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Discount created",
                        "schema": {
                            "$ref": "#/definitions/resmodel.NoDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            }
        },
        "/ndi/discount-product": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get all discount product targets",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discount Product Target"
                ],
                "summary": "List Discount Product Target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Discount product targets retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/resmodel.DatasResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "404": {
                        "description": "Discount product targets not found",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new discount product target",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discount Product Target"
                ],
                "summary": "Create Discount Product Target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to check",
                        "name": "X-Auth-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create discount product target",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/reqmodel.CreateDiscountProductTarget"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Discount product target created",
                        "schema": {
                            "$ref": "#/definitions/resmodel.NoDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            }
        },
        "/ndi/discount-product/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a discount product target by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discount Product Target"
                ],
                "summary": "Get Discount Product Target By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Discount Product Target ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Discount product target retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/resmodel.DataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "404": {
                        "description": "Discount product target not found",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing discount product target",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discount Product Target"
                ],
                "summary": "Update Discount Product Target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to check",
                        "name": "X-Auth-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Discount Product Target ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update discount product target",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/reqmodel.UpdateDiscountProductTarget"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Discount product target updated",
                        "schema": {
                            "$ref": "#/definitions/resmodel.NoDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete a discount product target",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discount Product Target"
                ],
                "summary": "Delete Discount Product Target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to check",
                        "name": "X-Auth-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Discount Product Target ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Discount product target deleted",
                        "schema": {
                            "$ref": "#/definitions/resmodel.NoDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            }
        },
        "/ndi/discount-transaction": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get all discount transaction targets",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discount Transaction Target"
                ],
                "summary": "List Discount Transaction Target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Discount transaction targets retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/resmodel.DatasResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "404": {
                        "description": "Discount transaction targets not found",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new discount transaction target",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discount Transaction Target"
                ],
                "summary": "Create Discount Transaction Target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to check",
                        "name": "X-Auth-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create discount transaction target",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/reqmodel.CreateDiscountTransactionTarget"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Discount transaction target created",
                        "schema": {
                            "$ref": "#/definitions/resmodel.NoDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            }
        },
        "/ndi/discount-transaction/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a discount transaction target by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discount Transaction Target"
                ],
                "summary": "Get Discount Transaction Target By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Discount Transaction Target ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Discount transaction target retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/resmodel.DataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "404": {
                        "description": "Discount transaction target not found",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing discount transaction target",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discount Transaction Target"
                ],
                "summary": "Update Discount Transaction Target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to check",
                        "name": "X-Auth-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Discount Transaction Target ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update discount transaction target",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/reqmodel.UpdateDiscountTransactionTarget"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Discount transaction target updated",
                        "schema": {
                            "$ref": "#/definitions/resmodel.NoDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete a discount transaction target",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discount Transaction Target"
                ],
                "summary": "Delete Discount Transaction Target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to check",
                        "name": "X-Auth-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Discount Transaction Target ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Discount transaction target deleted",
                        "schema": {
                            "$ref": "#/definitions/resmodel.NoDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            }
        },
        "/ndi/discount/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a discount by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discount"
                ],
                "summary": "Get Discount By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Discount ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Discount retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/resmodel.DataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "404": {
                        "description": "Discount not found",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing discount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discount"
                ],
                "summary": "Update Discount",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to check",
                        "name": "X-Auth-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Discount ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update discount",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/reqmodel.UpdateDiscount"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Discount updated",
                        "schema": {
                            "$ref": "#/definitions/resmodel.NoDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete a discount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discount"
                ],
                "summary": "Delete Discount",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to check",
                        "name": "X-Auth-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Discount ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Discount deleted",
                        "schema": {
                            "$ref": "#/definitions/resmodel.NoDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            }
        },
        "/ndi/post": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Mendapatkan seluruh post",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "List Post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Post berhasil diambil",
                        "schema": {
                            "$ref": "#/definitions/resmodel.DatasResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "404": {
                        "description": "Post not found",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Membuat post baru",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Create Post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to check",
                        "name": "X-Auth-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create post",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/reqmodel.CreatePost"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Post Created",
                        "schema": {
                            "$ref": "#/definitions/resmodel.NoDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            }
        },
        "/ndi/post/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Mendapatkan post berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Get Post By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Post berhasil diambil",
                        "schema": {
                            "$ref": "#/definitions/resmodel.DataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "404": {
                        "description": "Post not found",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Membuat post baru",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Update Post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to check",
                        "name": "X-Auth-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update post",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/reqmodel.UpdatePost"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Post Updated",
                        "schema": {
                            "$ref": "#/definitions/resmodel.NoDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Menghapus post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Delete Post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to check",
                        "name": "X-Auth-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Post Deleted",
                        "schema": {
                            "$ref": "#/definitions/resmodel.NoDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            }
        },
        "/ndi/product-discount-applied": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get all product discount applied",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product Discount Applied"
                ],
                "summary": "List Product Discount Applied",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Product discount applied retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/resmodel.DatasResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "404": {
                        "description": "Product discount applied not found",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new product discount applied",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product Discount Applied"
                ],
                "summary": "Create Product Discount Applied",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to check",
                        "name": "X-Auth-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create product discount applied",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/reqmodel.CreateProductDiscountApplied"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Product discount applied created",
                        "schema": {
                            "$ref": "#/definitions/resmodel.NoDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            }
        },
        "/ndi/product-discount-applied/by-discount/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a list of product discount applied by its discount ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product Discount Applied"
                ],
                "summary": "List Product Discount Applied By Discount ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product Discount ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Product discount applied retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/resmodel.DatasResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "404": {
                        "description": "Product discount applied not found",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            }
        },
        "/ndi/product-discount-applied/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete a product discount applied",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product Discount Applied"
                ],
                "summary": "Delete Product Discount Applied",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to check",
                        "name": "X-Auth-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Product Discount Applied ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Product discount applied deleted",
                        "schema": {
                            "$ref": "#/definitions/resmodel.NoDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            }
        },
        "/ndi/transaction-discount-applied": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get all transaction discount applied",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction Discount Applied"
                ],
                "summary": "List Transaction Discount Applied",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Product discount applied retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/resmodel.DatasResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "404": {
                        "description": "Product discount applied not found",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new transaction discount applied",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction Discount Applied"
                ],
                "summary": "Create Transaction Discount Applied",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to check",
                        "name": "X-Auth-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create transaction discount applied",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/reqmodel.CreateTransactionDiscountApplied"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Transaction discount applied created",
                        "schema": {
                            "$ref": "#/definitions/resmodel.NoDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            }
        },
        "/ndi/transaction-discount-applied/by-target/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a list of transaction discount applied by its discount target ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction Discount Applied"
                ],
                "summary": "List Transaction Discount Applied By Discount Target ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction Discount Target ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transaction discount applied retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/resmodel.DatasResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "404": {
                        "description": "Transaction discount applied not found",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            }
        },
        "/ndi/transaction-discount-applied/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete a transaction discount applied",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction Discount Applied"
                ],
                "summary": "Delete Transaction Discount Applied",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to check",
                        "name": "X-Auth-User-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Transaction Discount Applied ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transaction discount applied deleted",
                        "schema": {
                            "$ref": "#/definitions/resmodel.NoDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/utils.RequestError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "reqmodel.CreateDiscount": {
            "type": "object",
            "required": [
                "end_date",
                "name",
                "start_date",
                "type",
                "value"
            ],
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "reqmodel.CreateDiscountProductTarget": {
            "type": "object",
            "required": [
                "discount_id",
                "is_active",
                "target_id"
            ],
            "properties": {
                "discount_id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "max_total_quota": {
                    "type": "integer"
                },
                "price_after_discount": {
                    "type": "number"
                },
                "price_before_discount": {
                    "type": "number"
                },
                "product_name": {
                    "type": "string"
                },
                "target_id": {
                    "type": "string"
                },
                "total_discount": {
                    "type": "number"
                }
            }
        },
        "reqmodel.CreateDiscountTransactionTarget": {
            "type": "object",
            "required": [
                "discount_id",
                "is_active",
                "max_total_quota"
            ],
            "properties": {
                "discount_id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "max_total_quota": {
                    "type": "integer"
                }
            }
        },
        "reqmodel.CreatePost": {
            "type": "object",
            "required": [
                "content",
                "is_active",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "reqmodel.CreateProductDiscountApplied": {
            "type": "object",
            "required": [
                "discount_product_target_id"
            ],
            "properties": {
                "customer_id": {
                    "type": "string"
                },
                "customer_name": {
                    "type": "string"
                },
                "discount_product_target_id": {
                    "type": "string"
                },
                "transaction_date": {
                    "type": "string"
                }
            }
        },
        "reqmodel.CreateTransactionDiscountApplied": {
            "type": "object",
            "required": [
                "discount_transaction_target_id",
                "price_after_discount",
                "price_before_discount",
                "target_id",
                "total_discount"
            ],
            "properties": {
                "discount_transaction_target_id": {
                    "type": "string"
                },
                "price_after_discount": {
                    "type": "number"
                },
                "price_before_discount": {
                    "type": "number"
                },
                "target_id": {
                    "type": "string"
                },
                "total_discount": {
                    "type": "number"
                }
            }
        },
        "reqmodel.UpdateDiscount": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "reqmodel.UpdateDiscountProductTarget": {
            "type": "object",
            "required": [
                "discount_id",
                "is_active",
                "target_id"
            ],
            "properties": {
                "discount_id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "max_total_quota": {
                    "type": "integer"
                },
                "price_after_discount": {
                    "type": "number"
                },
                "price_before_discount": {
                    "type": "number"
                },
                "product_name": {
                    "type": "string"
                },
                "target_id": {
                    "type": "string"
                },
                "total_discount": {
                    "type": "number"
                }
            }
        },
        "reqmodel.UpdateDiscountTransactionTarget": {
            "type": "object",
            "properties": {
                "discount_id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "max_total_quota": {
                    "type": "integer"
                }
            }
        },
        "reqmodel.UpdatePost": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "resmodel.DataResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "resmodel.DatasResponse": {
            "type": "object",
            "properties": {
                "datas": {
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "type": "string"
                },
                "pagination": {},
                "success": {
                    "type": "boolean"
                }
            }
        },
        "resmodel.NoDataResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "utils.DataValidationError": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string",
                    "example": "email"
                },
                "message": {
                    "type": "string",
                    "example": "Invalid email address"
                }
            }
        },
        "utils.RequestError": {
            "type": "object",
            "properties": {
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/utils.DataValidationError"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Invalid email address"
                },
                "status_code": {
                    "type": "integer",
                    "example": 422
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Template Service Auth",
	Description:      "Template Service Auth Rest API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
